### ISSUE TITLE
开启less并不能直接使用less文件

### ISSUE THREAD

**Issue by brightcd** [wechat-miniprogram/miniprogram-custom-component#10]
1、其中tools/checkcomponents.js中有这么一句： componentListMap.wxssFileList.push(`${fileBase}.wxss`)
所以编译的时候只有wxss文件。

2、watch-wxss的任务是这样写的：gulp.watch('**/*.wxss', {cwd: srcPath, base: srcPath},。。。
less文件并不能被监听

ps：如果官方是支持在wxss文件中直接写less语法，那当我没说，请在readme中注明，谢谢~

**Comment by JuneAndGreen** [comment]
其实确实如你 ps 中所说来着，README.md 是有这句“支持 less 编写 wxss”，不过这里确实可能引起误解，我再注明一下。
