### ISSUE TITLE
使用模板时 GitHub 报 Security Alert 警告

### ISSUE THREAD

**Issue by yanshouwang** [wechat-miniprogram/miniprogram-custom-component#14]
GitHub 提示 package-lock.json 中的 lodash.template 需要更新， Upgrade lodash.template to version 4.5.0 or later
![image](https://user-images.githubusercontent.com/24455689/80294728-2eeba880-879e-11ea-920b-8ed8b931cc54.png)

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/80302309-cfac8900-87db-11ea-9d0a-75bbe0253883.png)

出自 gulp-install，已有提 issue：https://github.com/slushjs/gulp-install/issues/52，不过作者似乎许久没有进行处理。gulp-install 主要用于自动安装依赖包的，使用 gulp-util 是用来处理日志输出，目前看来不影响功能，仍然可以使用。

**Comment by yanshouwang** [comment]
官方的拖延症看起来很严重啊
