### ISSUE TITLE
使用ES6语法解构报错？

### ISSUE THREAD

**Issue by luojinghui** [wechat-miniprogram/miniprogram-custom-component#2]
![image](https://user-images.githubusercontent.com/12367406/48966393-99c60c80-f00b-11e8-9988-02c2e83d1ea1.png)
是要配置什么东西吗？

**Comment by luojinghui** [comment]
我在配置了`.babelrc`文件中配置了：
```bash
transform-es2015-spread
```
和使用了`babel-polyfill`:
```
module.exports = {
  entry: ["babel-polyfill", "index"]
};
```
都不行，求解。

**Comment by JuneAndGreen** [comment]
babel 相关问题请先搜索 babel 官网和社区吧。

附 object rest spread 的插件：https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread
