### ISSUE TITLE
组件lib.ts 中使用async/await，运行测试小程序报错

### ISSUE THREAD

**Issue by ganlanshugod** [wechat-miniprogram/miniprogram-custom-component#22]
lib.ts文件中编写了一个异步函数，使用了async和await关键字，运行时报如下错误：

`
![image](https://user-images.githubusercontent.com/8541176/130426409-5d8e4f44-cefa-4edf-a382-ec4413ab2671.png)

`

**Comment by JuneAndGreen** [comment]
这个模板比较老，后续会交棒给mpflow，不再单独维护这个模板了。回到这个问题，这是缺失了regeneratorRuntime，模板里的编译配置没有支持，根据自身需要手动补一下即可；或者也可以完全不过babel，直接交给工具的增强编译处理也行。
