### ISSUE TITLE
是否可支持less编译不处理import？

### ISSUE THREAD

**Issue by Joe-ling** [wechat-miniprogram/miniprogram-custom-component#6]
场景是这样的，我们使用您的组件脚手架，但我们有要求组件是多个打包放在一个脚手架内，且内部有一个全局组件主题的wxss文件（less语法）自由选择是否import，不希望编译之后每个组件样式把全局组件样式都打包进去文件内，而是继续作为一个独立的全局文件import。

**Comment by JuneAndGreen** [comment]
明白你的场景，之前也有考虑过不处理 import 的做法。现在最新版作了支持，可以更新下来试试。

**Comment by Joe-ling** [comment]
> 明白你的场景，之前也有考虑过不处理 import 的做法。现在最新版作了支持，可以更新下来试试。
感谢！
