### ISSUE TITLE
checkIncludedComponents时只处理目录下同名的wxss

### ISSUE THREAD

**Issue by Joe-ling** [wechat-miniprogram/miniprogram-custom-component#7]
在checkIncludedComponents时只处理目录下同名的wxss，wxml，js，json，其他不同名的文件不会被copy到目标目录。如：目录下有a,b两个wxss，a import了b，但因为某些原因我不用less编译，这时候编译时目标目录有a.wxss，b.wxss不会被复制。

**Comment by JuneAndGreen** [comment]
原意是希望放到 tools/config.js 中的 copy 配置里进行拷贝。在支持 #6 的时候同步支持分析依赖并进行拷贝，可以更新最新版试试。
