### ISSUE TITLE
开发环境开启eslint提示报错

### ISSUE THREAD

**Issue by lyseky** [wechat-miniprogram/miniprogram-custom-component#8]
ESLint: 'prop' is not defined. (no-undef）
ESLint: 'flag' is not defined. (no-undef）

**Comment by JuneAndGreen** [comment]
拿 demo 跑的还是跑的自己的代码？我本地跑 demo 正常，看你贴的信息就是有两个变量没有定义。

**Comment by JuneAndGreen** [comment]
开发者代码中存在使用未声明变量导致，故关闭。如还有其他疑问可新开 issue 或者 reopen。
