### ISSUE TITLE
匹配import的正则错误

### ISSUE THREAD

**Issue by oddjohn** [wechat-miniprogram/miniprogram-custom-component#9]
https://github.com/wechat-miniprogram/miniprogram-custom-component/blob/b3c0e6af8ecd44b5704af3afe02500e7992b7bcd/tools/checkwxss.js#L11
单引号匹配符里的[^']写成了[^"]，下面的end方法同样的错误

**Comment by JuneAndGreen** [comment]
ok，我修复一下
